# Generated by Django 5.0.4 on 2024-04-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='sexe',
            field=models.CharField(default='inconnu', max_length=10),
            preserve_default=False,
        ),
    ]
