# Generated by Django 5.0.4 on 2024-04-17 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_characters_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('U', 'Unknow')], max_length=1),
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childhood', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background', to='character.character')),
                ('defects', models.ManyToManyField(related_name='backgrounds', to='character.defect')),
                ('qualities', models.ManyToManyField(related_name='backgrounds', to='character.quality')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='character.character')),
            ],
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical', models.PositiveIntegerField()),
                ('agility', models.PositiveIntegerField()),
                ('comprehension', models.PositiveIntegerField()),
                ('intuition', models.PositiveIntegerField()),
                ('social', models.PositiveIntegerField()),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='character.character')),
            ],
        ),
    ]
