# Generated by Django 5.0.4 on 2024-04-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_defect_quality_alter_character_sexe_background_skill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='background',
            old_name='childhood',
            new_name='character',
        ),
        migrations.AddField(
            model_name='background',
            name='chillhood',
            field=models.CharField(default='maitre des sciences', max_length=100),
            preserve_default=False,
        ),
    ]
