# Generated by Django 5.0.4 on 2024-04-17 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_alter_background_chillhood'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.CharField(choices=[('physical', 'Physical'), ('agility', 'Agility'), ('comprehension', 'Comprehension'), ('intuition', 'Intuition'), ('social', 'Social')], max_length=100)),
                ('modifier_amout', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='defect',
            name='skill',
            field=models.ManyToManyField(null=True, related_name='defects', to='character.skill'),
        ),
        migrations.AddField(
            model_name='quality',
            name='skill',
            field=models.ManyToManyField(null=True, related_name='qualities', to='character.skill'),
        ),
        migrations.AddField(
            model_name='defect',
            name='stat_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.statmodifier'),
        ),
        migrations.AddField(
            model_name='quality',
            name='stat_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.statmodifier'),
        ),
    ]
