# Generated by Django 5.0.4 on 2024-04-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_skill_stat_modifier_characterskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='character',
        ),
    ]
