# Generated by Django 5.0.4 on 2024-04-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_remove_skill_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='character',
        ),
        migrations.AddField(
            model_name='character',
            name='agility',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='background',
            field=models.ManyToManyField(related_name='background', to='character.background'),
        ),
        migrations.AddField(
            model_name='character',
            name='comprehension',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='intuition',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='physical',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='social',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='background',
            name='defects',
            field=models.ManyToManyField(null=True, related_name='backgrounds', to='character.defect'),
        ),
        migrations.AlterField(
            model_name='background',
            name='qualities',
            field=models.ManyToManyField(null=True, related_name='backgrounds', to='character.quality'),
        ),
        migrations.DeleteModel(
            name='Statistique',
        ),
    ]
