# Generated by Django 5.0.4 on 2024-04-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_remove_background_character_character_agility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='defects',
            field=models.ManyToManyField(blank=True, related_name='backgrounds', to='character.defect'),
        ),
        migrations.AlterField(
            model_name='background',
            name='qualities',
            field=models.ManyToManyField(blank=True, related_name='backgrounds', to='character.quality'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='skill',
            field=models.ManyToManyField(blank=True, related_name='defects', to='character.skill'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='skill',
            field=models.ManyToManyField(blank=True, related_name='qualities', to='character.skill'),
        ),
    ]
