# Generated by Django 5.0.4 on 2024-04-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0011_alter_background_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quality',
            name='stat_modifier',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='stat_modifier',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='stat_modifier',
        ),
        migrations.AddField(
            model_name='skill',
            name='modifier_amount',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='stat_name',
            field=models.CharField(choices=[('physical', 'Physical'), ('agility', 'Agility'), ('comprehension', 'Comprehension'), ('intuition', 'Intuition'), ('social', 'Social')], default='comprehension', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StatModifier',
        ),
    ]
