# Generated by Django 5.0.4 on 2024-04-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0012_remove_quality_stat_modifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.CharField(choices=[('physical', 'Physical'), ('agility', 'Agility'), ('comprehension', 'Comprehension'), ('intuition', 'Intuition'), ('social', 'Social')], max_length=100)),
                ('modifier_amount', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='modifier_amount',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='stat_name',
        ),
    ]
