# Generated by Django 5.0.4 on 2024-04-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0013_statmodifier_remove_skill_modifier_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatModifier',
        ),
        migrations.AddField(
            model_name='skill',
            name='stat_modifiers',
            field=models.JSONField(default=list),
        ),
    ]
