# Generated by Django 5.0.4 on 2024-04-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0014_delete_statmodifier_skill_stat_modifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.PositiveIntegerField(default='8'),
            preserve_default=False,
        ),
    ]
